### ISSUE TITLE
Splitting issue.

### ISSUE THREAD

**Issue by NoGoat** [giffi-dev/SMBAutoSplitter#1]
Well, during my MWE ending runs, it refuses to split in 1 - 1. Other splits are working fine.

**Comment by miklaskarjalainen** [comment]
I tried it out on MWE and for me atleast it works.

You could give more information about the issue like:
Does it only happen on the japanese fds rom, does it work on ntsc?
Is it splitting at all in 1-1 or is it just inconsistent?
